data:
  train_path: data/quickstart/train.jsonl
  valid_path: data/quickstart/valid.jsonl
model:
  batch_size: 8
  max_seq_length: 2048
  name: microsoft/phi-3-mini-4k-instruct
training:
  grad_checkpoint: true
  save_every: 100
