# Gemma 2-2B specific configuration
model:
  name: "google/gemma-2-2b"
  path: "google/gemma-2-2b"
  batch_size: 1
  max_seq_length: 512
  learning_rate: 1.5e-4
  num_layers: 4

# Training parameters
training:
  seed: 42
  iters: 600
  val_batches: 20
  steps_per_report: 10
  steps_per_eval: 50
  save_every: 100
  grad_checkpoint: true

# LoRA configuration based on Gemma architecture
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_layers: 4
