# Phi-3 Mini specific configuration
model:
  name: "microsoft/phi-3-mini-4k-instruct"
  path: "microsoft/phi-3-mini-4k-instruct"
  batch_size: 1
  max_seq_length: 512
  learning_rate: 2.0e-4
  num_layers: 4

# Training parameters
training:
  seed: 42
  iters: 600
  val_batches: 20
  steps_per_report: 10
  steps_per_eval: 50
  save_every: 100
  grad_checkpoint: true

# LoRA configuration
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules:
    - "attn.Wq"
    - "attn.Wk"
    - "attn.Wv"
    - "attn.out_proj"
    - "mlp.up_proj"
    - "mlp.down_proj"
    - "mlp.gate_proj"
  lora_layers: 4
