# Qwen 2.5 7B Instruct specific configuration
model:
  name: "Qwen/Qwen2.5-7B-Instruct"
  path: "Qwen/Qwen2.5-7B-Instruct"
  batch_size: 1
  max_seq_length: 32768
  learning_rate: 1.0e-4
  num_layers: 28

# Training parameters
training:
  seed: 42
  iters: 600
  val_batches: 20
  steps_per_report: 10
  steps_per_eval: 50
  save_every: 100
  grad_checkpoint: true

# LoRA configuration based on Qwen architecture
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules:
    - "c_attn"
    - "c_proj"
    - "w1"
    - "w2"
    - "c_proj"
  lora_layers: 28
